/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OracleRouteImport } from './routes/oracle'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ApiPublicTestLlmRouteImport } from './routes/api/public/test-llm'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OracleRoute = OracleRouteImport.update({
  id: '/oracle',
  path: '/oracle',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTestLlmRoute = ApiPublicTestLlmRouteImport.update({
  id: '/api/public/test-llm',
  path: '/api/public/test-llm',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/oracle': typeof OracleRoute
  '/reports': typeof ReportsRoute
  '/api/public/test-llm': typeof ApiPublicTestLlmRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/oracle': typeof OracleRoute
  '/reports': typeof ReportsRoute
  '/api/public/test-llm': typeof ApiPublicTestLlmRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/oracle': typeof OracleRoute
  '/reports': typeof ReportsRoute
  '/api/public/test-llm': typeof ApiPublicTestLlmRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/oracle' | '/reports' | '/api/public/test-llm'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/oracle' | '/reports' | '/api/public/test-llm'
  id: '__root__' | '/' | '/oracle' | '/reports' | '/api/public/test-llm'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OracleRoute: typeof OracleRoute
  ReportsRoute: typeof ReportsRoute
  ApiPublicTestLlmRoute: typeof ApiPublicTestLlmRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oracle': {
      id: '/oracle'
      path: '/oracle'
      fullPath: '/oracle'
      preLoaderRoute: typeof OracleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/test-llm': {
      id: '/api/public/test-llm'
      path: '/api/public/test-llm'
      fullPath: '/api/public/test-llm'
      preLoaderRoute: typeof ApiPublicTestLlmRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OracleRoute: OracleRoute,
  ReportsRoute: ReportsRoute,
  ApiPublicTestLlmRoute: ApiPublicTestLlmRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
